// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"gf-user/api/account"
)

type ControllerLogin struct{}

func NewLogin() account.IAccountLogin {
	return &ControllerLogin{}
}

type ControllerUser struct{}

func NewUser() account.IAccountUser {
	return &ControllerUser{}
}
