// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package storage

import (
	"gf-user/api/storage"
)

type ControllerV1 struct{}

func NewV1() storage.IStorageV1 {
	return &ControllerV1{}
}

type ControllerRedirect struct{}

func NewRedirect() storage.IStorageRedirect {
	return &ControllerRedirect{}
}
