// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-user/internal/dao/internal"
)

// internalAccountDao is an internal type for wrapping the internal DAO implementation.
type internalAccountDao = *internal.AccountDao

// accountDao is the data access object for the table account.
// You can define custom methods on it to extend its functionality as needed.
type accountDao struct {
	internalAccountDao
}

var (
	// Account is a globally accessible object for table account operations.
	Account = accountDao{
		internal.NewAccountDao(),
	}
)

// Add your custom methods and functionality below.
