// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-user/internal/dao/internal"
)

// internalAppDao is an internal type for wrapping the internal DAO implementation.
type internalAppDao = *internal.AppDao

// appDao is the data access object for the table app.
// You can define custom methods on it to extend its functionality as needed.
type appDao struct {
	internalAppDao
}

var (
	// App is a globally accessible object for table app operations.
	App = appDao{
		internal.NewAppDao(),
	}
)

// Add your custom methods and functionality below.
