// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-user/internal/dao/internal"
)

// internalSpaceDao is an internal type for wrapping the internal DAO implementation.
type internalSpaceDao = *internal.SpaceDao

// spaceDao is the data access object for the table space.
// You can define custom methods on it to extend its functionality as needed.
type spaceDao struct {
	internalSpaceDao
}

var (
	// Space is a globally accessible object for table space operations.
	Space = spaceDao{
		internal.NewSpaceDao(),
	}
)

// Add your custom methods and functionality below.
