// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package config

import (
	"gf-user/api/config"
)

type ControllerV1 struct{}

func NewV1() config.IConfigV1 {
	return &ControllerV1{}
}

type ControllerPublic struct{}

func NewPublic() config.IConfigPublic {
	return &ControllerPublic{}
}
