// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sdk

import (
	"gf-user/api/sdk"
)

type ControllerToken struct{}

func NewToken() sdk.ISdkToken {
	return &ControllerToken{}
}

type ControllerApp struct{}

func NewApp() sdk.ISdkApp {
	return &ControllerApp{}
}
